export const Events = [
	{
		year: "2024",
		events: [
			{
				category: "event",
				guest_id: [],
				title: "Cracking the Google Interview",
				imageUrl: "./guests/default_image.webp",
				href: "https://www.eventbrite.it/e/biglietti-cracking-the-google-interview-with-a-special-guest-1083851963399?aff=oddtdtcreator",
				description: "Superhero Valley returns to Pisa with a new in-person event! Join us to discover the secrets to face a tech interview for Big Tech companies.",
				year: "2024",
				month: "11",
				day: "26",
				time: "18:00"
		    },
			{
				category: "event",
				guest_id: [53],
				title: "Università all'estero e ricerca applicata su Large Language Models",
				imageUrl: "./guests/linda_friso.webp",
				href: "https://bit.ly/sv_friso",
				description: "Linda è Machine Learning Engineer in Google! In questo talk ci parlerà della sua carriera, dagli studi in Matematica, le olimpiadi di Matematica, lo studio da autodidatta alla programmazione, fino ad approdare in Google, dove giornalmente lavora ai Large Language Models.",
				year: "2024",
				month: "11",
				day: "25",
				time: "18:30"
		    },
			{
				category: "event",
				guest_id: [],
				title: 'The Mentorship Program',
				imageUrl: "./guests/default_image.webp",
				href: "https://bit.ly/sv_mentorship24",
				description: "Evento di presentazione del Mentorship Program 2024-2025 di Superhero Valley",
				year: "2024",
				month: "11",
				day: "18",
				time: "18:30"
		    },
			{
				category: "event",
				guest_id: [],
				title: 'How to Mock Interview',
				imageUrl: "./guests/default_image.webp",
				href: 'https://bit.ly/notarstefano24',
				description: "Jacopo Notarstefano è senior software engineer ad Amazon! In questo talk vedremo come si conduce una technical mock interview come si fa nelle Big Tech. Ad essere intervistato un membro della community, che si districherà tra le domande dell'interviewer, tra feedback e tips da usare durante un colloquio vero.",
				year: "2024",
				month: "11",
				day: "11",
				time: "18:30"
		    },
			{
				category: "event",
				guest_id: [],
				title: 'Come ho trovato lavoro in Big Tech',
				imageUrl: "./guests/default_image.webp",
				href: 'https://bit.ly/48qEFaY',
				description: "In questo panel Sara, Marco e Gabriele ci racconteranno percorso che li ha portati dall'università ad essere Software Engineer in Uber, Google e Grammarly. Chiederemo a Sara, Marco e Gabriele dei suggerimenti per prepararsi alle interview e cercheremo di capire come Superhero Valley è stata utile nella ricerca di un lavoro in big tech.",
				year: "2024",
				month: "10",
				day: "28",
				time: "18:30"
		    },
			{
				category: "event",
				guest_id: [14],
				title: 'Come scrivere il CV!',
				imageUrl: "/guests/diego_ceccarelli.webp",
				href: 'https://bit.ly/ceccarelli_2024',
				description: 'Diego Ceccarelli è AI Engineering Manager in Bloomberg! Ci racconterà come strutturare un CV da mandare ad una Big Tech company!',
				year: "2024",
				month: "10",
				day: "21",
				time: "18:30"
		    },
			{
				category: "event",
				guest_id: [6],
				title: "The IT interview process... is fundamentally broken!",
				imageUrl: "/guests/nicola_corti.webp",
				href: 'https://bit.ly/sv_corti24',
				description: "Nicola è Staff Engineer a Meta, ci parlerà di come affrontare i colloqui in Big Tech.",
				year: "2024",
				month: "10",
				day: "14",
				time: "19:30"
			},
			{
				category: "event",
				guest_id: [],
				title: "Superhero Valley - La Nuova Stagione",
				imageUrl: "./guests/default_image.webp",
				href: 'https://bit.ly/stagione25',
				description: "La nuova stagione di Superhero Valley è iniziata! Abbiamo introdotto i nuovi membri alla community, a ciò che facciamo portando anche al testimonianza dei precedenti mentee ed i loro risultati.",
				year: "2024",
				month: "10",
				day: "07",
				time: "18:30"
			},
			{
				category: "event",
				guest_id: [46],
				title: "Il sogno americano",
				imageUrl: "./guests/alessandro_gnoli.webp",
				href: 'https://bit.ly/sv_gnoli',
				description: "Alessandro è Engineering Manager in Google US. Prima di entrare in Google ha lavorato come Engineering Manager in una Series B startup (Raise) e come Software Engineer per Expedia. Durante il talk parlerà di come si lavora legalmente in negli States partendo dall'Italia, delle tipologie di visti disponibili e come scegliere il visto giusto, il trade-off tra lavorare in Italia e negli States.",
				year: "2024",
				month: "05",
				day: "20",
				time: "18:30"
			},
			{
				category: "event",
				guest_id: [52],
				title: "Becoming a relevant Software Engineer",
				imageUrl: "./guests/francesco_napoletano.webp",
				href: 'https://bit.ly/sv_napo',
				description: "Francesco (Napo) è Staff Software Engineer in Sysdig. Durante il talk ci parlerà del suo percorso lavorativo, come rimanere rilevanti nell'industria software dopo 40 anni, carrer ladder, performance e peer review tecniche, differenze tra Big Tech (Sysdig, eBay) e Italian tech (Subito.it), e cosa lo spinge a contribuire all'OSS.",
				year: "2024",
				month: "05",
				day: "06",
				time: "18:30"
			},
			{
				category: "event",
				guest_id: [51],
				title: "Dall'Italia a San Francisco",
				imageUrl: "./guests/gianluca_venturini.webp",
				href: 'https://teams.microsoft.com/registration/MWtFxyCi9Ue-Ukc4KGcKoQ,5_gfHHKx0EeoQWa01OBRBg,IAHVGT0EY0yWBrRcV_CNBg,K7L0n4ZUlUem2ULaf_5Zbw,0LSNOH8By0mLFG7MNz8IQg,jVzUcVDp80O40e4k8xpyAg?mode=read&tenantId=c7456b31-a220-47f5-be52-473828670aa1',
				description: "Gianluca è Software Engineer in Material Security a San Francisco. Durante il talk ci parlerà del suo percorso accademico, del suo trasferimento dall'Italia a Chicago e poi San Francisco, ed esperienze lavorative in Dropbox corporate e Unicorn startup Material Security.",
				year: "2024",
				month: "04",
				day: "22",
				time: "18:00"
			},
			{
				category: "event",
				guest_id: [50],
				title: 'My path to Amazon',
				imageUrl: "./guests/jacopo_notarstefano.webp",
				href: 'https://teams.microsoft.com/registration/MWtFxyCi9Ue-Ukc4KGcKoQ,5_gfHHKx0EeoQWa01OBRBg,IAHVGT0EY0yWBrRcV_CNBg,x93xuOJOk0-GvXwO2RE6kQ,Ox47Mqwtp02cH1YL-GNC6w,g3r72TZh_EWxmyEFCiFPkQ?mode=read&tenantId=c7456b31-a220-47f5-be52-473828670aa1',
				description: "Oggi Jacopo è Senior SDE nel team che si occupa di Availability per AWS Aurora, il RDBMS proprietario creato per il Cloud con piena compatibilità con MySQL e PostgreSQL. In passato è stato fra i primi ingegneri della startup Nabla Technologies, ed ha cominciato la propria carriera al CERN come Fellow.",
				year: "2024",
				month: "04",
				day: "08",
				time: "18:30"
			},
			{
				category: "event",
				guest_id: [49],
				title: 'Dalla Sicilia a JP Morgan',
				imageUrl: "./guests/gabriele_cinà.webp",
				href: 'https://teams.microsoft.com/registration/MWtFxyCi9Ue-Ukc4KGcKoQ,fZgCURkwfEmdzdEMLIx66Q,88pVMgzq6kmFEO9b39dczA,xUCD36NAQkeNlY2CjxK3sA,66SieDHk6E6_ajVjTrsaUg,v1J-UqS7LE6TOHG4g_w6-Q?mode=read&tenantId=c7456b31-a220-47f5-be52-473828670aa1',
				description: "Gabriele è Software Engineer in JP Morgan a Londra. Durante il talk ci parlerà del suo percorso accademico e della sua avventura da startupper, come ci si prepara per le interview in Fintech, ottenere una internship in JP Morgan e return offer.",
				year: "2024",
				month: "03",
				day: "25",
				time: "19:00"
			},
			{
				category: "event",
				guest_id: [48],
				title: 'Ricerca applicata in contesti industriali e transizioni IC/manager',
				imageUrl: "./guests/diego_perino.webp",
				href: 'https://teams.microsoft.com/registration/MWtFxyCi9Ue-Ukc4KGcKoQ,5_gfHHKx0EeoQWa01OBRBg,IAHVGT0EY0yWBrRcV_CNBg,Yt_AHdp8J0elluLP5sAfhw,-IkS8uFrdESeKGnmiYgNjg,2MtGVdiVPEK67l5nRbyPMg?mode=read&tenantId=c7456b31-a220-47f5-be52-473828670aa1',
				description: "Diego Perino è attualmente Engineering Manager nel team di Generative AI a Meta. Ha lavorato come IC e manager in Telefonica Research, Bell Labs e Orange Labs. Durante il talk ci parlerà del suo percorso, di come ha visto la ricerca applicata in vari contesti e di come durante la sua carrierà sia riuscito a saltare varie volte dal ruolo di Individual Contributor a Manager e viceversa.",
				year: "2024",
				month: "03",
				day: "18",
				time: "18:00"
			},
			{
				category: "event",
				guest_id: [47],
				title: 'My Path to Microsoft',
				imageUrl: "./guests/davide_pollicino.webp",
				href: 'https://www.twitch.tv/superherovalley',
				description: "Davide è Software Engineer in Microsoft a Praga. Prima di entrare in Microsoft ha studiato ad Edinburgo (UK) ed ha avuto esperienza come Product Manager in una startup. Durante il talk discuterà del suo periodo di studi in UK, come le attività di mentorship (prima di mentee e poi da mentor) abbiano assunto un ruolo cruciale nel suo percorso di crescita e dell'arrivo in Microsoft.",
				year: "2024",
				month: "03",
				day: "11",
				time: "18:30"
			},
			{
				category: "event",
				guest_id: [],
				title: 'From zero to Superhero: Episode 3 -  Big Tech Coding Mock Interview',
				imageUrl: "./guests/default_image.webp",
				href: 'https://www.twitch.tv/superherovalley',
				description: "In questo terzo episodio, gli Hero trainer Stefano Ivancich (SWE @ Uber, Ex-AWS) ed Emanuele Triuzzi (SWE @ Bending Spoons) ti spiegheranno come funziona e come ci si prepara per la coding interview in Big Tech! Durante la live membro della community di Superhero Valley verrà sottoposto ad una simulazione di colloquio tecnico!",
				year: "2024",
				month: "02",
				day: "26",
				time: "18:30"
			},
			{
				category: "event",
				guest_id: [],
				title: 'From zero to Superhero: Episode 2 -  Big Tech Behavioural Interview',
				imageUrl: "./guests/default_image.webp",
				href: 'https://www.twitch.tv/superherovalley',
				description: "In questo secondo episodio, gli Hero trainer Stefano Ivancich (SWE @ Uber, Ex-AWS) ed Emanuele Triuzzi (SWE @ Bending Spoons) ti spiegheranno come funziona e come ci si prepara la behavioural interview in Big Tech! Ma soprattutto come rispondere alle domande di rito del team di recruiting e lo STAR framework!",
				year: "2024",
				month: "01",
				day: "31",
				time: "18:30"
			},
			{
				category: "event",
				guest_id: [],
				title: 'From zero to Superhero: Episode 1 -  How to write a CV',
				imageUrl: "./guests/default_image.webp",
				href: 'https://www.twitch.tv/superherovalley',
				description: "Non sai come scrivere il CV? Superhero Valley va in live su Twitch con gli Hero trainer Stefano Ivancich (SWE @ Uber, Ex-AWS) ed Emanuele Triuzzi (SWE @ Bending Spoons) per spiegarti come scrivere un CV professionale da zero, con tips and tricks per le FAANG!",
				year: "2024",
				month: "01",
				day: "22",
				time: "18:30"
			},
		]
	},
	{
		year: "2023",
		events: [
			{
		            	category: "event",
		            	guest_id: [46],
		                title: 'From Individual Contributor to Manager con Alessandro Gnoli',
		                imageUrl: "./guests/alessandro_gnoli.webp",
		                href: 'https://teams.microsoft.com/registration/MWtFxyCi9Ue-Ukc4KGcKoQ,fZgCURkwfEmdzdEMLIx66Q,88pVMgzq6kmFEO9b39dczA,4zHDmQ4Fg0aZeY-yPlE2jg,hwLTCgO9nEWju4I3S-CEDA,lxSq22Iqg0iPj5qMkOwKJQ?mode=read&tenantId=c7456b31-a220-47f5-be52-473828670aa1',
		                description: 'Alessandro è Engineering Manager in Google US. Prima di entrare in Google ha lavorato come Engineering Manager in una Series B startup (Raise) e come Software Engineer per Expedia. Al talk discuterà il ruolo del manager e darà alcuni consigli su come affrontare la transizione da Individual Contributor (IC) a Manager e i trade-off rispetto alla carriera da Staff/Principal IC.',
				year: "2023",
				month: "12",
				day: "11",
        			time: "18:30"
			},
			{
		            	category: "event",
		            	guest_id: [45],
		                title: 'Former CTO at IO Interactive - AMA',
		                imageUrl: "./guests/maurizio_de_pascale.webp",
		                href: 'https://teams.microsoft.com/registration/MWtFxyCi9Ue-Ukc4KGcKoQ,fZgCURkwfEmdzdEMLIx66Q,88pVMgzq6kmFEO9b39dczA,3e7uPZT65EOq2Ubv5JYWGQ,ImKIsa45yEaFWo9cB_KE9g,UFUXou3TO0GBYozgxoLIsA?mode=read&tenantId=c7456b31-a220-47f5-be52-473828670aa1',
		                description: "Maurizio è attualmente Techical Advisor nell’industria dei videogiochi, ha una esperienza di 15 anni nello sviluppo dei videogiochi AAA! Ha assunto il ruolo di CTO per alcuni titoli della serie Hitman in IO Interactive e ancor prima ha lavorato come Technical Architect su Rainbow Six Siege per Ubisoft. Durante il talk Maurizio ci parlerà della sua avventura in questa meravigliosa industria!",
				year: "2023",
				month: "12",
				day: "04",
        			time: "18:30"
            		},
			{
		            	category: "event",
		            	guest_id: [],
		                title: 'The Mentorship Program',
		                imageUrl: "./guests/default_image.webp",
		                href: 'https://teams.microsoft.com/registration/MWtFxyCi9Ue-Ukc4KGcKoQ,fZgCURkwfEmdzdEMLIx66Q,88pVMgzq6kmFEO9b39dczA,lLlXpcN_-kK9qs5UNxBsoA,7p3LUor9QE-zuBPpi_fwrg,X-AO0dQ3ekWZUFGapadtsg?mode=read&tenantId=c7456b31-a220-47f5-be52-473828670aa1',
		                description: 'Evento di presentazione del Mentorship Program 2023-2024 di Superhero Valley',
				year: "2023",
				month: "11",
				day: "27",
				time: "18:30"
            		},
			{
		            	category: "event",
		            	guest_id: [44],
		                title: 'My career path con Tommaso Dreossi',
		                imageUrl: "/guests/tommaso_dreossi.webp",
		                href: 'https://teams.microsoft.com/registration/MWtFxyCi9Ue-Ukc4KGcKoQ,fZgCURkwfEmdzdEMLIx66Q,88pVMgzq6kmFEO9b39dczA,qnh97Kc770uwoDKhHEpLwg,XB7rAKew6UK-wNaNasPl1Q,8Irro7UU8UW21DS1tBgNIQ?mode=read&tenantId=c7456b31-a220-47f5-be52-473828670aa1',
		                description: 'Tommaso ha ottenuto il dottorato presso l’Université Grenoble Alpes in Computer Science, ha svolto il post-doc a Berkeley per diventare Applied Scientist in Amazon. Attualmente lavora come Staff Machine Learning Scientist nella startup Insitro, fondata da Daphne Koller, Professor of Computer Science at Stanford University.',
				year: "2023",
				month: "11",
				day: "20",
	        		time: "18:30"
		        },
			{
				category: "event",
				guest_id: [22],
				title: 'How to... mock interview con Diego Puppin',
				imageUrl: "/guests/diego_puppin.webp",
				href: 'https://bit.ly/3Q0zmWS',
				description: 'Diego è Staff Software Engineer a Synthesia, in questo evento parlerà di come si affronta una mock interview',
				year: "2023",
				month: "11",
				day: "13",
				time: "18:30"
	            	},
	            	{
		                category: "event",
		            	guest_id: [14],
		                title: 'How to... write a CV con Diego Ceccarelli',
		                imageUrl: "/guests/diego_ceccarelli.webp",
		                href: 'https://bit.ly/4016LoO',
				description: 'Diego è AI Team Leader a Bloomberg, in questo evento parlerà di come scrivere un CV',
		                date: '13 Novembre 2023 18:30',
				year: "2023",
				month: "11",
				day: "06",
		                time: "18:30"
	           	},
	           	{
		                category: "event",
		            	guest_id: [3],
		                title: 'My path to Google con Federico Scloza',
		                imageUrl: "./guests/default_image.webp",
		                href: 'https://bit.ly/3Q9zrrs',
		                description: 'Federico è Software Engineer in Google, ci parlerà del suo percorso fino a Google',
				year: "2023",
				month: "10",
				day: "30",
		                time: "18:30"
			},
			{
		                category: "event",
		            	guest_id: [],
		                title: 'Live da Mr. Rip',
		                imageUrl: "./guests/mr_rip.webp",
		                href: 'https://www.twitch.tv/retireinprogress/',
		                description: 'Evento live da Mr. Rip dove abbiamo parlato di Superhero Valley',
				year: "2023",
				month: "10",
				day: "26",
		                time: "21:30"
			},
			{
				category: "event",
		            	guest_id: [6],
		                title: 'The Tech Interview process is fundamentally broken con Nicola Corti',
		                imageUrl: "/guests/nicola_corti.webp",
		                href: 'https://bit.ly/3QklVCv',
		                date: '23 Ottobre 2023 18:30',
		                description: 'Nicola è Staff Engineer a Meta, ci parlerà di come affrontare i colloqui in Big Tech',
				year: "2023",
				day: "23",
				month: "10",    
		                time: "18:30"
	            	},
			{
		            	category: "event",
		            	guest_id: [],
		            	title: "Superhero Valley - La Nuova Stagione 3",
		            	href: "",
		            	description: "Ebbene si, la nuova stagione di Superhero Valley è iniziata! Abbiamo introdotto i nuovi membri alla community, a ciò che facciamo portando anche al testimonianza dei precedenti mentee ed i loro risultati.",
				year: "2023",
		            	month: "10",
				day: "16",
	        	},
			{
				category: "event",
				guest_id: [43],
				title: "Tecnical Leader in R&D C- UAS and Post-Quantum Cryptography",
				href: "/superheroes",
				description: "Mark Diamantino Caribé è un ingegnere di cybersicurezza presso Thales. Durante il talk, Mark condividerà le sue conoscenze ed esperienze nel campo della crittografia post-quantistica e del ruolo di un leader tecnico in R&D C-UAS. Tratterà temi come le sfide e le opportunità della crittografia nell'era post-quantistica, l'importanza del leadership tecnico nella ricerca e sviluppo di C-UAS, e il ruolo della cybersicurezza in questo contesto emergente. ",
				year: "2023",
				month: "06",
				day: "19",
			},
			{
				category: "event",
				guest_id: [42],
				title: "Managing High-Performing Engineering Teams in Big Tech",
				href: "/superheroes",
				description: "Luca è Senior Engineering Manager in Uber, durante il talk condividerà le strategie da adottare per gestire al meglio un High-Performing Engineering Team. Si parlerà di talent acquisition, team optimization, goal setting e professional growth in Big Tech.",
				year: "2023",
				month: "06",
				day: "12",
			},
			{
				category: "event",
				guest_id: [41],
				title: "I, Robot",
				href: "/superheroes",
				description: "Fernando è Senior Robotics Software Engineer in Dyson. Ci racconterà dei suoi traguardi in Italia come Robotics Software Engineer presso l'Istituto Italiano di Teconologia (iit) e lo sviluppo di Robotics Software per i dispotivi Dyson nel campus di Hullavington (UK).",
				year: "2023",
				month: "06",
				day: "07",
			},
			{
				category: "event",
				guest_id: [40],
				title: "Program Management in Big Tech",
				href: "/superheroes",
				description: "Marco è attualmente Tech Startup Advisor, è stato Program Manager in Kraken, Google e Nokia. Durante il talk racconterà della sua avventura dall'informatica al program management, quali sono i compiti di un Program Manager nelle Big Tech e della sua esperienza da freelance come Tech Startup Advisor.",
				year: "2023",
				month: "05",
				day: "30",
			},
			{
				category: "event",
				guest_id: [39],
				title: "From C++ To Kernel Engineering",
				href: "/superheroes",
				description: "Vladislav è Senior MTS Kernel Engineer a VMware, ci racconterà della sua avventura da developer in C++ a Kernel Engineer. Durante il talk Vladislav parlerà della sua esperienza nel mondo del lavoro fin da giovane, la passione per Linux, il suo contributo personale al mondo open source ed il trasferimento in Silicon Valley.",
				year: "2023",
				month: "05",
				day: "22",
			},
			{
				category: "event",
				guest_id: [38],
				title: "Quantum Computing is like magic",
				href: "/superheroes",
				description: "Jordan is Tech Evangelist AWS Braket. In this talk she will talk about Quantum Computing, especially in Amazon",
				year: "2023",
				month: "05",
				day: "19",
			},
			{
				category: "event",
				guest_id: [37],
				title: "Sognando la California",
				href: "/superheroes",
				description: "Alberto è HPC DevOps Engineer in Seqera Labs. Dopo aver passato un periodo a Berkeley è tornato in Italia e non vede l'ora di raccontarci come si vive in California",
				year: "2023",
				month: "05",
				day: "15",
			},
			{
				category: "event",
				guest_id: [36],
				title: "My path to Crazyness",
				href: "/superheroes",
				description: "Alberto è Senior Machine Learning Engineer a Meta, ci racconterà della sua 'folle' esperienza. Durante il talk Alberto parlerà della sua esperienza e preparazione per i colloqui prima in JP Morgan e poi in Meta.",
				year: "2023",
				month: "04",
				day: "04",
			},
			{
				category: "event",
				guest_id: [35],
				title: "My path to Google",
				href: "/superheroes",
				description: "Antonino è Site Reliability Manager a Google, ci racconterà della sua molteplice esperienza nelle big tech. Durante il talk avremo modo di capire come Antonino sia arrivato prima alla Sun Microsystems, poi Amazon ed infine in Google.",
				year: "2023",
				month: "03",
				day: "29",
			},
			{
				category: "event",
				guest_id: [34],
				title: "Augmented and Virtual Reality from a Software Engineer point of view",
				href: "/superheroes",
				description: "Alberto Taiuti è 3D Software Engineer in Skydio, ha lavorato su Augmented e Virtual Reality in Apple ed ha co-fondato Luma AI.",
				year: "2023",
				month: "02",
				day: "27",
			},
			{
				category: "event",
				guest_id: [33],
				title: "Antonio Gulli live a Pisa",
				href: "/superheroes",
				description: "Antonio Gulli è Senior Director in Google. In questa live presso l'Università di Pisa avremo modo di scoprire la storia di Antonio, da Pisa fino a Zurigo in Google passando per il dottorato di ricerca e la sua esperienza nel mondo startup e nella difficoltà di portare una azienda come Ask ad investire in Italia.",
				year: "2023",
				month: "02",
				day: "20",
			},
			{
				category: "event",
				guest_id: [32],
				title: "My path to Software Engineering at Google",
				href: "/superheroes",
				description: "Nancy is a Software Engineer in Google. In this talk we deep dive on how to grok the technical interview process",
				year: "2023",
				month: "02", 
				day: "06",
			},
			{
				category: "event",
				guest_id: [31],
				title: "My path to Google",
				href: "/superheroes",
				description: "Simone è Machine Learning Software Engineer in Google. Durante il talk ci parlerà di come perfezionare il CV e prepararsi ai colloqui per le FAANG",
				year: "2023",
				month: "02",
				day: "02",
			},	
		],
	},
	{
		year: "2022",
		events: [
			{
				category: "event",
				guest_id: [27],
				title: "From Open Source to Microsoft",
				href: "/superheroes",
				description: "Lorenzo è Senior Software Engineer a Microsoft ci racconterà del fil rouge della sua carriera: open source. Durante il talk avremo modo di chiedere a Lorenzo come si faccia a contribuire a progetti open source e quanto possano essere utili per farsi notare dalle big tech.",
				year: "2022",
				month: "12",
				day: "12",
			},
			{
				category: "event",
				guest_id: [29],
				title: "My path to Meta",
				href: "/superheroes",
				description: "Alberto è Production Engineer a Meta ed in questo talk avremo l’occasione di farci raccontare del suo percorso che passa attraverso l’amore per Linux, il Machine Learning, l'odio nei confronti dei miner delle crypto ed essere assunto in una Big Tech come Meta.",
				year: "2022",
				month: "12",
				day: "5",
			},
			{
				category: "event",
				guest_id: [30],
				title: "La carriera piena di intoppi (?) di Roberto Clapis",
				href: "/superheroes",
				description: "Come si fa a diventare esperti in un ambito tecnico? Quali sono i rischi di tentare questo tipo di carriera? A che punto dell'evoluzione professionale si può essere sicuri nel proprio percorso, e quando invece si rischia di commettere sviste evitabili? Questo talk proverà a dare delle risposte ripercorrendo la carriera piena di intoppi di Roberto Clapis.",
				year: "2022",
				month: "11",
				day: "28",
			},
			{
				category: "event",
				guest_id: [28],
				title: "Dall'industria all'accademia",
				href: "/superheroes",
				description: "Fabrizio ha avuto in passato in ricerca in aziende come Yahoo! Research e Facebook AI. Oltre a queste esperienze di ricerca, è stato anche software engineer sempre a Facebook. Oggi è professore ordinario alla Sapienza.",
				year: "2022",
				month: "11",
				day: "14",
			},
			{
				category: "event",
				guest_id: [6],
				title: "Come affrontare il colloquio nelle FAANG",
				href: "/superheroes",
				description: "Nicola è Senior Android Engineer e durante il talk ci racconterà di come funziona il processo di colloquio nelle Big Tech company",
				year: "2022",
				month: "11",
				day: "7",
			},
			{
				category: "event",
				guest_id: [26],
				title: "Un italiano in Nvidia",
				href: "/superheroes",
				description: "Marco ci racconterà del suo percorso lavorativo ed, in particolare, di cosa lo ha condotto ad Nvidia!",
				year: "2022",
				month: "10",
				day: "24",
			},
			{
				category: "event",
				guest_id: [14],
				title: "Scrivere un CV per le FAANG",
				href: "/superheroes",
				description: "Diego Ceccarelli, AI Team Leader a Bloomberg, ci racconterà come strutturare un CV da mandare ad una Big Tech company!",
				year: "2022",
				month: "10",
				day: "17",
			},
			{
				category: "event",
				guest_id: [1],
				title: "Google AMA con Christian Burrini",
				href: "/superheroes",
				description: "Evento in presenza a Pisa con Christian Burrini, sessione di Ask me anything",
				year: "2022",
				month: "06",
				day: "24",
			},
			{
				category: "event",
				guest_id: [22],
				title: "Da Pisa a Twitter con Diego Puppin",
				href: "/superheroes",
				description: "Diego è Staff Software Engineer a Twitter e, Lunedì 2 Maggio alle 21:30, avremo il piacere di ospitarlo a parlarci del suo percorso che lo ha portato a Twitter!",
				year: "2022",
				month: "05",
				day: "02",
			},
			{
				category: "event",
				guest_id: [23],
				title: "Dal Texas Instruments Ti99/4a alla Silicon Valley",
				href: "/superheroes",
				description: "Enrico Zimuel, Principal Software Engineer ad Elastic, ci racconterà della sua esperienza lavorativa e di cosa è significato per lui lavorare in Silicon Valley. Per chi non conoscesse Elastic, è una società quotata in borsa Americana - Olandese. Elasticsearch, è il motore di ricerca da loro sviluppato ed usato da grandi aziende come eBay, Wikipedia, Yelp, Uber, Lyft, Tinder e Netflix.",
				year: "2022",
				month: "04",
				day: "26",
			},
			{
				category: "event",
				guest_id: [],
				title: "Path to Google leveraging competing offers",
				href: "/superheroes",
				description: "Ludovico Bessi, Software Engineer - Machine Learning, di Google ci racconterà di alcune tips sul processo di recruiting e sulla negoziazione delle offerte di lavoro nelle Big Tech.",
				year: "2022",
				month: "04",
				day: "11",
			},
			{
				category: "event",
				guest_id: [20, 19, 15],
				title: "",
				href: "/superheroes",
				description: "Lunedì 21/03 alle 18:30 avremo il talk di 3 ragazzi di Apple! Filippo Bigarella - Security Engineer Niccolo’ Giovannelli - Engineering Project Manager Giovanni Tarducci - Senior iOS Engineer Filippo, Niccolo’ e Giovanni ci racconteranno della loro esperienza e di cosa li ha portati ad Apple!",
				year: "2022",
				month: "03",
				day: "21",
			},
			{
				category: "event",
				guest_id: [24],
				title: "Mia-Platform",
				href: "/superheroes",
				description: "On Monday 14/03 at 18:30, Michel Murabito will talk about Mia-Platform. Is Mia-Platform a FAANG company? Obviously no. But for sure is one of the most promising Italian tech companies that acquired international attention. We want to encourage these realities giving Mia-Platform a space to talk about itself :)",
				year: "2022",
				month: "03",
				day: "14",
			},
			{
				category: "event",
				guest_id: [25],
				title: "Google talk",
				href: "/superheroes",
				description: "This Friday at 18:30, Yerlan Baiturinov will talk about his path to Google. It is an occasion for us to ask him some questions :)",
				year: "2022",
				month: "03",
				day: "04",
			},
			{
				category: "event",
				guest_id: [24],
				title: "Netflix",
				href: "/superheroes",
				description: "We are glad to announce that, on Monday 28/02 at 19:00, Mattia Toso, Senior Software Engineer at Netflix, will talk about his experience!",
				year: "2022",
				month: "02",
				day: "25",
			},
			{
				category: "event",
				guest_id: [5],
				title: "Google",
				href: "/superheroes",
				description: "We are glad to announce that on Monday 7/02 at 18:00, Shahed Shahriar SRE @Google will reveal to us some tips to prepare for Coding Competitions like Google Hashcode! We recall that we created a Virtual Hub for the Hashcode with the name [Italy] SuperHeroes Valley - GDG Pisa - DSC Pisa - GDG Cloud Torino. So, if you intend to participate in the Hashcode, feel free to join us :)",
				year: "2022",
				month: "02",
				day: "07",
			},
		],
	},
	{
		year: "2021",
		events: [
			{
				category: "event",
				guest_id: [],
				title: "Superheroes QUIZ GAME",
				href: "/superheroes",
				description: "Organizzeremo un quiz game al quale tutti voi potrete partecipare e, chi risponderà correttamente a più domande, vincerà la prima maglietta di Superhero Valley! ",
				year: "2021",
				month: "12",
				day: "15",
			},
			{
				category: "event",
				guest_id: [17],
				title: "Hiring at Bloomberg",
				href: "/superheroes",
				description: "Francesca ci parlerà della realtà di Bloomberg, di come avviene il processo di recruiting e quali sono le caratteristiche che si cercano in una persona da assumere.",
				year: "2021",
				month: "11",
				day: "22",
			},
			{
				category: "event",
				guest_id: [7],
				title: "In Office vs Remote",
				href: "/superheroes",
				description: "Diego Colombo è tornato e ci parlerà delle differenze tra lavorare 'In Office' vs 'Remote'. In particolare, di quali sono i vantaggi e gli svantaggi...",
				year: "2021",
				month: "11",
				day: "15",
			},
			{
				category: "event",
				guest_id: [16],
				title: "Diversity in Microsoft",
				href: "/superheroes",
				description: "Erika is Director of People & Culture in the Developer Division at Microsoft where she leads the organizational culture change strategy. In this talk she will talk about Leadership, Inclusion and Diversity and why they are foundamentals to work in Big Tech.",
				year: "2021",
				month: "11",
				day: "9",
			},
			{
				category: "event",
				guest_id: [14],
				title: "CV Review by Diego Ceccarelli",
				href: "/superheroes",
				description: "Diego terrà un talk su come scrivere un CV e farà anche uno screening live dei CV.",
				year: "2021",
				month: "10",
				day: "25",
			},
			{
				category: "event",
				guest_id: [6],
				title: "Come sono strutturati i colloqui nelle FAANG",
				href: "/superheroes",
				description: "In questo talk Nicola Corti ci parlerà del funzionamento dei colloqui in FAANG e di come sia 'semplice' passarli con la giusta preparazione.",
				year: "2021",
				month: "10",
				day: "18",
			},
			{
				category: "event",
				guest_id: [1],
				title: "Hello, Superheroes!",
				href: "/superheroes",
				description: "Una nuova stagione di Superhero Valley sta per iniziare :)",
				year: "2021",
				month: "10",
				day: "11",
			},
			{
				category: "event",
				guest_id: [15],
				title: "Security Engineering in Apple",
				href: "/superheroes",
				description: "Filippo Bigarella è Security Engineer in Apple.",
				year: "2021",
				month: "06",
				day: "14",
			},
			{
				category: "event",
				guest_id: [14],
				title: "Data Science in Bloomberg",
				href: "/superheroes",
				description: "Diego Ceccarelli è AI Team Leader in Bloomberg. Ci parlerà del suo percorso accademico fino ad approdare in Bloomberg.",
				year: "2021",
				month: "05",
				day: "31",
			},
			{
				category: "event",
				guest_id: [12, 13],
				title: "Software Engineering in Bending Spoons",
				href: "/superheroes",
				description: "Federico Cergol e Silvia Trebini ci parleranno della loro esperienza in Bending Spoons, rispettivamente di Software Engineering e Talent Acquisition.",
				year: "2021",
				month: "05",
				day: "03",
			},
			{
				category: "event",
				guest_id: [10],
				title: "Fuga di Cervelli",
				href: "/superheroes",
				description: "Il fenomeno italano della fuga di cervelli",
				year: "2021",
				month: "04",
				day: "12",
			},
			{
				category: "event",
				guest_id: [8],
				title: "Epic Games",
				href: "/superheroes",
				description: "Maurizio Sciglio è Director in Epic Games.",
				year: "2021",
				month: "03",
				day: "29",
			},
			{
				category: "event",
				guest_id: [7],
				title: "Software Engineering in Microsoft",
				href: "/superheroes",
				description: "Diego Colombo è Principal Software Engineer in Microsoft, durante il talk parlerà del suo approdo in Microsoft passando per l'italiana Milestone e per Citi.",
				year: "2021",
				month: "03",
				day: "22",
			},
			{
				category: "event",
				guest_id: [],
				title: "Evento Live - Mock Interview",
				href: "/superheroes",
				description: "Evento live faremo delle mock interview.",
				year: "2021",
				month: "03",
				day: "08",
			},
			{
				category: "event",
				guest_id: [],
				title: "Evento Live",
				href: "/superheroes",
				description: "Evento live dove parleremo di cosa ci occupiamo in Superhero Valley.",
				year: "2021",
				month: "03",
				day: "01",
			},
			{
				category: "event",
				guest_id: [6],
				title: "The IT Interview Process... is fundamentally Broken!",
				href: "/superheroes",
				description: "In questo talk Nicola Corti ci parlerà del funzionamento dei colloqui in Big Tech e di come sia 'semplice' passarli con la giusta preparazione.",
				year: "2021",
				month: "02",
				day: "22",
			},
			{
				category: "event",
				guest_id: [],
				title: "How to approach competitions",
				href: "/superheroes",
				description: "In questo talk parleremo di come utilizzare le competizioni a nostro vantaggio e come affrontarle al meglio.",
				year: "2021",
				month: "02",
				day: "15",
			},
			{
				category: "event",
				guest_id: [4],
				title: "Mock interview in Meta",
				href: "/superheroes",
				description: "Samuele Maci farà una mock interview in stile Meta.",
				year: "2021",
				month: "02",
				day: "08",
			},
			{
				category: "event",
				guest_id: [4],
				title: "Production Engineering in Meta",
				href: "/superheroes",
				description: "Samuele Maci è Production Engineer in Meta. Durante il talk parlerà della sua professione e della sua carriera in Meta.",
				year: "2021",
				month: "02",
				day: "01",
			},
			{
				category: "event",
				guest_id: [],
				title: "Evento Live - SuperSocial",
				href: "/superheroes",
				description: "Evento live dove parleremo di cosa ci occupiamo in Superhero Valley.",
				year: "2021",
				month: "01",
				day: "25",
			},
			{
				category: "event",
				guest_id: [3],
				title: "Mock interview in Google",
				href: "/superheroes",
				description: "Federico Scloza farà una mock interview in stile Google.",
				year: "2021",
				month: "01",
				day: "18",

			},
		],
	},
	{
		year: "2020",
		events: [
			{
				category: "event",
				guest_id: [1],
				title: "Interview best practice",
				href: "/superheroes",
				description: "Durante questo talk Christian Burrini dispenserà molti consigli su come superare al meglio il colloquio.",
				year: "2020",
				month: "12",
				day: "20",
			},
			{
				category: "event",
				guest_id: [2],
				title: "Nei panni di un SRE in Google",
				href: "/superheroes",
				description: "Lisa Vitolo è SRE in Google, durante il talk ci spiegherà cosa fa un SRE e come è arrivata in Google passando per la Google Summer of Code!",
				year: "2020",
				month: "12",
				day: "14",
			},
			{
				category: "event",
				guest_id: [],
				title: "Il nostro primo evento live",
				href: "/superheroes",
				description:  "Questo è il nostro primo evento dal vivo dove presentiamo al mondo Superhero Valley :)",
				year: "2020",
				month: "10",
				day: "26",
			},
		],
	},
];
