export const Events = [
	{
		year: "2023",
		events: [
            {
            	category: "event",
            	guest_id: [],
                title: 'How to... mock interview con Diego Puppin',
                imageUrl: "/guests/diego_puppin.webp",
                href: 'https://bit.ly/3Q0zmWS',
                description: 'Diego è Staff Software Engineer a Synthesia, in questo evento parlerà di come si affronta una mock interview',
				year: "2023",
				day: 13",
				month: "11",
            },
            {
                category: "event",
            	guest_id: [],
                title: 'How to... write a CV con Diego Ceccarelli',
                imageUrl: "/guests/diego_ceccarelli.webp",
                href: 'https://bit.ly/4016LoO',
                date: '13 Novembre 2023 18:30',
				year: "2023",
				day: "06",
				month: "11",
                description: 'Diego è AI Team Leader a Bloomberg, in questo evento parlerà di come scrivere un CV',
            },
            {
                category: "event",
            	guest_id: [],
				year: "2023",
				day: "30",
				month: "10",
                title: 'My path to Google con Federico Scloza',
                imageUrl: "./guests/default_img.png",
                href: 'https://bit.ly/3Q9zrrs',
                description: 'Federico è Software Engineer in Google, ci parlerà del suo percorso fino a Google',
            },
            {
                title: 'The Tech Interview process is fundamentally broken con Nicola Corti',
                imageUrl: "/guests/nicola_corti.webp",
                href: 'https://bit.ly/3QklVCv',
                date: '23 Ottobre 2023 18:30',
                description: 'Nicola è Staff Engineer a Meta, ci parlerà di come affrontare i colloqui in Big Tech',
                category: "event",
            	guest_id: [],
				year: "2023",
				day: "23",
				month: "10",
            },
			{
            	category: "event",
            	guest_id: [],
            	title: "Superhero Valley - La Nuova Stagione 3",
            	href: "",
            	year: "2023",
            	day: "16",
            	month: "10",
            	description:
            	"Ebbene si, la nuova stagione di Superhero Valley è iniziata! Abbiamo introdotto i nuovi membri alla community, a ciò che facciamo portando anche al testimonianza dei precedenti mentee ed i loro risultati.",
        	},
			{
				category: "event",
				guest_id: [43],
				title: "Tecnical Leader in R&D C- UAS and Post-Quantum Cryptography",
				href: "/superheroes",
				year: "2023",
				day: "19",
				month: "06",
				description:
				"Mark Diamantino Caribé è un ingegnere di cybersicurezza presso Thales. Durante il talk, Mark condividerà le sue conoscenze ed esperienze nel campo della crittografia post-quantistica e del ruolo di un leader tecnico in R&D C-UAS. Tratterà temi come le sfide e le opportunità della crittografia nell'era post-quantistica, l'importanza del leadership tecnico nella ricerca e sviluppo di C-UAS, e il ruolo della cybersicurezza in questo contesto emergente. ",
			},
			{
				category: "event",
				guest_id: [42],
				title: "Managing High-Performing Engineering Teams in Big Tech",
				href: "/superheroes",
				year: "2023",
				day: "12",
				month: "06",
				description:
				"Luca è Senior Engineering Manager in Uber, durante il talk condividerà le strategie da adottare per gestire al meglio un High-Performing Engineering Team. Si parlerà di talent acquisition, team optimization, goal setting e professional growth in Big Tech.",
			},
			{
				category: "event",
				guest_id: [41],
				title: "I, Robot",
				href: "/superheroes",
				year: "2023",
				day: "07",
				month: "06",
				description:
				"Fernando è Senior Robotics Software Engineer in Dyson. Ci racconterà dei suoi traguardi in Italia come Robotics Software Engineer presso l'Istituto Italiano di Teconologia (iit) e lo sviluppo di Robotics Software per i dispotivi Dyson nel campus di Hullavington (UK).",
			},
			{
				category: "event",
				guest_id: [40],
				title: "Program Management in Big Tech",
				href: "/superheroes",
				year: "2023",
				day: "30",
				month: "05",
				description:
				"Marco è attualmente Tech Startup Advisor, è stato Program Manager in Kraken, Google e Nokia. Durante il talk racconterà della sua avventura dall'informatica al program management, quali sono i compiti di un Program Manager nelle Big Tech e della sua esperienza da freelance come Tech Startup Advisor.",
			},
			{
				category: "event",
				guest_id: [39],
				title: "From C++ To Kernel Engineering",
				href: "/superheroes",
				year: "2023",
				day: "22",
				month: "05",
				description:
				"Vladislav è Senior MTS Kernel Engineer a VMware, ci racconterà della sua avventura da developer in C++ a Kernel Engineer. Durante il talk Vladislav parlerà della sua esperienza nel mondo del lavoro fin da giovane, la passione per Linux, il suo contributo personale al mondo open source ed il trasferimento in Silicon Valley.",
			},
			{
				category: "event",
				guest_id: [38],
				title: "Quantum Computing is like magic",
				href: "/superheroes",
				year: "2023",
				day: "19",
				month: "05",
				description:
				"Jordan is Tech Evangelist AWS Braket. In this talk she will talk about Quantum Computing, especially in Amazon",
			},
			{
				category: "event",
				guest_id: [37],
				title: "Sognando la California",
				href: "/superheroes",
				year: "2023",
				day: "15",
				month: "05",
				description:
				"Alberto è HPC DevOps Engineer in Seqera Labs. Dopo aver passato un periodo a Berkeley è tornato in Italia e non vede l'ora di raccontarci come si vive in California",
			},
			{
				category: "event",
				guest_id: [36],
				title: "My path to Crazyness",
				href: "/superheroes",
				year: "2023",
				day: "04",
				month: "04",
				description:
				"Alberto è Senior Machine Learning Engineer a Meta, ci racconterà della sua 'folle' esperienza. Durante il talk Alberto parlerà della sua esperienza e preparazione per i colloqui prima in JP Morgan e poi in Meta.",
			},
			{
				category: "event",
				guest_id: [35],
				title: "My path to Google",
				href: "/superheroes",
				year: "2023",
				day: "29",
				month: "03",
				description:
				"Antonino è Site Reliability Manager a Google, ci racconterà della sua molteplice esperienza nelle big tech. Durante il talk avremo modo di capire come Antonino sia arrivato prima alla Sun Microsystems, poi Amazon ed infine in Google.",
			},
			{
				category: "event",
				guest_id: [34],
				title: "Augmented and Virtual Reality from a Software Engineer point of view",
				href: "/superheroes",
				year: "2023",
				day: "27",
				month: "02",
				description:
				"Alberto Taiuti è 3D Software Engineer in Skydio, ha lavorato su Augmented e Virtual Reality in Apple ed ha co-fondato Luma AI.",
			},
			{
				category: "event",
				guest_id: [33],
				title: "Antonio Gulli live a Pisa",
				href: "/superheroes",
				year: "2023",
				day: "20",
				month: "02",
				description:
				"Antonio Gulli è Senior Director in Google. In questa live presso l'Università di Pisa avremo modo di scoprire la storia di Antonio, da Pisa fino a Zurigo in Google passando per il dottorato di ricerca e la sua esperienza nel mondo startup e nella difficoltà di portare una azienda come Ask ad investire in Italia.",
			},
			{
				category: "event",
				guest_id: [32],
				title: "My path to Software Engineering at Google",
				href: "/superheroes",
				year: "2023",
				day: "06",
				month: "02",
				description:
				"Nancy is a Software Engineer in Google. In this talk we deep dive on how to grok the technical interview process",
			},
			{
				category: "event",
				guest_id: [31],
				title: "My path to Google",
				href: "/superheroes",
				year: "2023",
				day: "02",
				month: "02",
				description:
				"Simone è Machine Learning Software Engineer in Google. Durante il talk ci parlerà di come perfezionare il CV e prepararsi ai colloqui per le FAANG",
			},
		],
	},
	{
		year: "2022",
		events: [
			{
				category: "event",
				guest_id: [27],
				title: "From Open Source to Microsoft",
				href: "/superheroes",
				year: "2022",
				day: "12",
				month: "12",
				description:
				"Lorenzo è Senior Software Engineer a Microsoft ci racconterà del fil rouge della sua carriera: open source. Durante il talk avremo modo di chiedere a Lorenzo come si faccia a contribuire a progetti open source e quanto possano essere utili per farsi notare dalle big tech.",
			},
			{
				category: "event",
				guest_id: [29],
				title: "My path to Meta",
				href: "/superheroes",
				year: "2022",
				day: "5",
				month: "12",
				description:
				"Alberto è Production Engineer a Meta ed in questo talk avremo l’occasione di farci raccontare del suo percorso che passa attraverso l’amore per Linux, il Machine Learning, l'odio nei confronti dei miner delle crypto ed essere assunto in una Big Tech come Meta.",
			},
			{
				category: "event",
				guest_id: [30],
				title: "La carriera piena di intoppi (?) di Roberto Clapis",
				href: "/superheroes",
				year: "2022",
				day: "28",
				month: "11",
				description:
				"Come si fa a diventare esperti in un ambito tecnico? Quali sono i rischi di tentare questo tipo di carriera? A che punto dell'evoluzione professionale si può essere sicuri nel proprio percorso, e quando invece si rischia di commettere sviste evitabili? Questo talk proverà a dare delle risposte ripercorrendo la carriera piena di intoppi di Roberto Clapis.",
			},
			{
				category: "event",
				guest_id: [28],
				title: "Dall'industria all'accademia",
				href: "/superheroes",
				year: "2022",
				day: "14",
				month: "11",
				description: "Fabrizio ha avuto in passato in ricerca in aziende come Yahoo! Research e Facebook AI. Oltre a queste esperienze di ricerca, è stato anche software engineer sempre a Facebook. Oggi è professore ordinario alla Sapienza.",
			},
			{
				category: "event",
				guest_id: [6],
				title: "Come affrontare il colloquio nelle FAANG",
				href: "/superheroes",
				year: "2022",
				day: "7",
				month: "11",
				description: "Nicola è Senior Android Engineer e durante il talk ci racconterà di come funziona il processo di colloquio nelle Big Tech company",
			},
			{
				category: "event",
				guest_id: [26],
				title: "Un italiano in Nvidia",
				href: "/superheroes",
				year: "2022",
				day: "24",
				month: "10",
				description: "Marco ci racconterà del suo percorso lavorativo ed, in particolare, di cosa lo ha condotto ad Nvidia!",
			},
			{
				category: "event",
				guest_id: [14],
				title: "Scrivere un CV per le FAANG",
				href: "/superheroes",
				year: "2022",
				day: "17",
				month: "10",
				description: "Diego Ceccarelli, AI Team Leader a Bloomberg, ci racconterà come strutturare un CV da mandare ad una Big Tech company!",
			},
			{
				category: "event",
				guest_id: [1],
				title: "Google AMA con Christian Burrini",
				href: "/superheroes",
				year: "2022",
				day: "24",
				month: "06",
				description: "Evento in presenza a Pisa con Christian Burrini, sessione di Ask me anything",
			},
			{
				category: "event",
				guest_id: [22],
				title: "Da Pisa a Twitter con Diego Puppin",
				href: "/superheroes",
				year: "2022",
				day: "02",
				month: "05",
				description:
					"Diego è Staff Software Engineer a Twitter e, Lunedì 2 Maggio alle 21:30, avremo il piacere di ospitarlo a parlarci del suo percorso che lo ha portato a Twitter!",
			},
			{
				category: "event",
				guest_id: [23],
				title: "Dal Texas Instruments Ti99/4a alla Silicon Valley",
				href: "/superheroes",
				year: "2022",
				day: "26",
				month: "04",
				description:
					"Enrico Zimuel, Principal Software Engineer ad Elastic, ci racconterà della sua esperienza lavorativa e di cosa è significato per lui lavorare in Silicon Valley. Per chi non conoscesse Elastic, è una società quotata in borsa Americana - Olandese. Elasticsearch, è il motore di ricerca da loro sviluppato ed usato da grandi aziende come eBay, Wikipedia, Yelp, Uber, Lyft, Tinder e Netflix.",
			},
			{
				category: "event",
				guest_id: [],
				title: "Path to Google leveraging competing offers",
				href: "/superheroes",
				year: "2022",
				day: "11",
				month: "04",
				description:
					"Ludovico Bessi, Software Engineer - Machine Learning, di Google ci racconterà di alcune tips sul processo di recruiting e sulla negoziazione delle offerte di lavoro nelle Big Tech.",
			},
			{
				category: "event",
				guest_id: [20, 19, 15],
				title: "",
				href: "/superheroes",
				year: "2022",
				day: "21",
				month: "03",
				description:
					"Lunedì 21/03 alle 18:30 avremo il talk di 3 ragazzi di Apple! Filippo Bigarella - Security Engineer Niccolo’ Giovannelli - Engineering Project Manager Giovanni Tarducci - Senior iOS Engineer Filippo, Niccolo’ e Giovanni ci racconteranno della loro esperienza e di cosa li ha portati ad Apple!",
			},
			{
				category: "event",
				guest_id: [24],
				title: "Mia-Platform",
				href: "/superheroes",
				year: "2022",
				day: "14",
				month: "03",
				description:
					"On Monday 14/03 at 18:30, Michel Murabito will talk about Mia-Platform. Is Mia-Platform a FAANG company? Obviously no. But for sure is one of the most promising Italian tech companies that acquired international attention. We want to encourage these realities giving Mia-Platform a space to talk about itself :)",
			},
			{
				category: "event",
				guest_id: [25],
				title: "Google talk",
				href: "/superheroes",
				year: "2022",
				day: "04",
				month: "03",
				description:
					"This Friday at 18:30, Yerlan Baiturinov will talk about his path to Google. It is an occasion for us to ask him some questions :)",
			},
			{
				category: "event",
				guest_id: [24],
				title: "Netflix",
				href: "/superheroes",
				year: "2022",
				day: "25",
				month: "02",
				description:
					"We are glad to announce that, on Monday 28/02 at 19:00, Mattia Toso, Senior Software Engineer at Netflix, will talk about his experience!",
			},
			{
				category: "event",
				guest_id: [5],
				title: "Google",
				href: "/superheroes",
				year: "2022",
				day: "07",
				month: "02",
				description:
					"We are glad to announce that on Monday 7/02 at 18:00, Shahed Shahriar SRE @Google will reveal to us some tips to prepare for Coding Competitions like Google Hashcode! We recall that we created a Virtual Hub for the Hashcode with the name [Italy] SuperHeroes Valley - GDG Pisa - DSC Pisa - GDG Cloud Torino. So, if you intend to participate in the Hashcode, feel free to join us :)",
			},
		],
	},
	{
		year: "2021",
		events: [
			{
				category: "event",
				guest_id: [],
				title: "Superheroes QUIZ GAME",
				href: "/superheroes",
				year: "2021",
				day: "15",
				month: "12",
				description: "Organizzeremo un quiz game al quale tutti voi potrete partecipare e, chi risponderà correttamente a più domande, vincerà la prima maglietta di SuperheroesValley! ",
			},
			{
				category: "event",
				guest_id: [17],
				title: "Hiring at Bloomberg",
				href: "/superheroes",
				year: "2021",
				day: "22",
				month: "11",
				description: "Francesca ci parlerà della realtà di Bloomberg, di come avviene il processo di recruiting e quali sono le caratteristiche che si cercano in una persona da assumere.",
			},
			{
				category: "event",
				guest_id: [7],
				title: "In Office vs Remote",
				href: "/superheroes",
				year: "2021",
				day: "15",
				month: "11",
				description: "Diego Colombo è tornato e ci parlerà delle differenze tra lavorare 'In Office' vs 'Remote'. In particolare, di quali sono i vantaggi e gli svantaggi...",
			},
			{
				category: "event",
				guest_id: [16],
				title: "Diversity in Microsoft",
				href: "/superheroes",
				year: "2021",
				day: "9",
				month: "11",
				description: "Erika is Director of People & Culture in the Developer Division at Microsoft where she leads the organizational culture change strategy. In this talk she will talk about Leadership, Inclusion and Diversity and why they are foundamentals to work in Big Tech.",
			},
			{
				category: "event",
				guest_id: [14],
				title: "CV Review by Diego Ceccarelli",
				href: "/superheroes",
				year: "2021",
				day: "25",
				month: "10",
				description: "Diego terrà un talk su come scrivere un CV e farà anche uno screening live dei CV.",
			},
			{
				category: "event",
				guest_id: [6],
				title: "Come sono strutturati i colloqui nelle FAANG",
				href: "/superheroes",
				year: "2021",
				day: "18",
				month: "10",
				description: "In questo talk Nicola Corti ci parlerà del funzionamento dei colloqui in FAANG e di come sia 'semplice' passarli con la giusta preparazione.",
			},
			{
				category: "event",
				guest_id: [1],
				title: "Hello, Superheroes!",
				href: "/superheroes",
				year: "2021",
				day: "11",
				month: "10",
				description: "Una nuova stagione di Superhero Valley sta per iniziare :)",
			},
			{
				category: "event",
				guest_id: [15],
				title: "Security Engineering in Apple",
				href: "/superheroes",
				year: "2021",
				day: "14",
				month: "06",
				description: "Filippo Bigarella è Security Engineer in Apple.",
			},
			{
				category: "event",
				guest_id: [14],
				title: "Data Science in Bloomberg",
				href: "/superheroes",
				year: "2021",
				day: "31",
				month: "05",
				description: "Diego Ceccarelli è AI Team Leader in Bloomberg. Ci parlerà del suo percorso accademico fino ad approdare in Bloomberg.",
			},
			{
				category: "event",
				guest_id: [12, 13],
				title: "Software Engineering in Bending Spoons",
				href: "/superheroes",
				year: "2021",
				day: "03",
				month: "05",
				description: "Federico Cergol e Silvia Trebini ci parleranno della loro esperienza in Bending Spoons, rispettivamente di Software Engineering e Talent Acquisition.",
			},
			{
				category: "event",
				guest_id: [10],
				title: "Fuga di Cervelli",
				href: "/superheroes",
				year: "2021",
				day: "12",
				month: "04",
				description: "Il fenomeno italano della fuga di cervelli",
			},
			{
				category: "event",
				guest_id: [8],
				title: "Epic Games",
				href: "/superheroes",
				year: "2021",
				day: "29",
				month: "03",
				description: "Maurizio Sciglio è Director in Epic Games.",
			},
			{
				category: "event",
				guest_id: [7],
				title: "Software Engineering in Microsoft",
				href: "/superheroes",
				year: "2021",
				day: "22",
				month: "03",
				description: "Diego Colombo è Principal Software Engineer in Microsoft, durante il talk parlerà del suo approdo in Microsoft passando per l'italiana Milestone e per Citi.",
			},
			{
				category: "event",
				guest_id: [],
				title: "Evento Live - Mock Interview",
				href: "/superheroes",
				year: "2021",
				day: "08",
				month: "03",
				description: "Evento live faremo delle mock interview.",
			},
			{
				category: "event",
				guest_id: [],
				title: "Evento Live",
				href: "/superheroes",
				year: "2021",
				day: "01",
				month: "03",
				description: "Evento live dove parleremo di cosa ci occupiamo in Superhero Valley.",
			},
			{
				category: "event",
				guest_id: [6],
				title: "The IT Interview Process... is fundamentally Broken!",
				href: "/superheroes",
				year: "2021",
				day: "22",
				month: "02",
				description: "In questo talk Nicola Corti ci parlerà del funzionamento dei colloqui in Big Tech e di come sia 'semplice' passarli con la giusta preparazione.",
			},
			{
				category: "event",
				guest_id: [],
				title: "How to approach competitions",
				href: "/superheroes",
				year: "2021",
				day: "15",
				month: "02",
				description: "In questo talk parleremo di come utilizzare le competizioni a nostro vantaggio e come affrontarle al meglio.",
			},
			{
				category: "event",
				guest_id: [4],
				title: "Mock interview in Meta",
				href: "/superheroes",
				year: "2021",
				day: "08",
				month: "02",
				description: "Samuele Maci farà una mock interview in stile Meta.",
			},
			{
				category: "event",
				guest_id: [4],
				title: "Production Engineering in Meta",
				href: "/superheroes",
				year: "2021",
				day: "01",
				month: "02",
				description: "Samuele Maci è Production Engineer in Meta. Durante il talk parlerà della sua professione e della sua carriera in Meta.",
			},
			{
				category: "event",
				guest_id: [],
				title: "Evento Live - SuperSocial",
				href: "/superheroes",
				year: "2021",
				day: "25",
				month: "01",
				description: "Evento live dove parleremo di cosa ci occupiamo in Superhero Valley.",
			},
			{
				category: "event",
				guest_id: [3],
				title: "Mock interview in Google",
				href: "/superheroes",
				year: "2021",
				day: "18",
				month: "01",
				description: "Federico Scloza farà una mock interview in stile Google.",
			},
		],
	},
	{
		year: "2020",
		events: [
			{
				category: "event",
				guest_id: [1],
				title: "Interview best practice",
				href: "/superheroes",
				year: "2020",
				day: "20",
				month: "12",
				description: "Durante questo talk Christian Burrini dispenserà molti consigli su come superare al meglio il colloquio.",
			},
			{
				category: "event",
				guest_id: [2],
				title: "Nei panni di un SRE in Google",
				href: "/superheroes",
				year: "2020",
				day: "14",
				month: "12",
				description: "Lisa Vitolo è SRE in Google, durante il talk ci spiegherà cosa fa un SRE e come è arrivata in Google passando per la Google Summer of Code!",
			},
			{
				category: "event",
				guest_id: [],
				title: "Il nostro primo evento live",
				href: "/superheroes",
				year: "2020",
				day: "26",
				month: "10",
				description:  "Questo è il nostro primo evento dal vivo dove presentiamo al mondo Superhero Valley :)",
			},
		],
	},
];
