export const PastEvents = [
	{
		year: "2023",
		events: [
			{
				category: "event",
				guest_id: [43],
				title: "Tecnical Leader in R&D C- UAS and Post-Quantum Cryptography",
				href: "/superheroes",
				year: "2023",
				day: "19",
				month: "06",
				descriprion:
				"Mark Diamantino Caribé è un ingegnere di cybersicurezza presso Thales. Durante il talk, Mark condividerà le sue conoscenze ed esperienze nel campo della crittografia post-quantistica e del ruolo di un leader tecnico in R&D C-UAS. Tratterà temi come le sfide e le opportunità della crittografia nell'era post-quantistica, l'importanza del leadership tecnico nella ricerca e sviluppo di C-UAS, e il ruolo della cybersicurezza in questo contesto emergente. ",
			},
			{
				category: "event",
				guest_id: [42],
				title: "Managing High-Performing Engineering Teams in Big Tech",
				href: "/superheroes",
				year: "2023",
				day: "12",
				month: "06",
				descriprion:
				"Luca è Senior Engineering Manager in Uber, durante il talk condividerà le strategie da adottare per gestire al meglio un High-Performing Engineering Team. Si parlerà di talent acquisition, team optimization, goal setting e professional growth in Big Tech.",
			},
			{
				category: "event",
				guest_id: [41],
				title: "I, Robot",
				href: "/superheroes",
				year: "2023",
				day: "07",
				month: "06",
				descriprion:
				"Fernando è Senior Robotics Software Engineer in Dyson. Ci racconterà dei suoi traguardi in Italia come Robotics Software Engineer presso l'Istituto Italiano di Teconologia (iit) e lo sviluppo di Robotics Software per i dispotivi Dyson nel campus di Hullavington (UK).",
			},
			{
				category: "event",
				guest_id: [40],
				title: "Program Management in Big Tech",
				href: "/superheroes",
				year: "2023",
				day: "30",
				month: "05",
				descriprion:
				"Marco è attualmente Tech Startup Advisor, è stato Program Manager in Kraken, Google e Nokia. Durante il talk racconterà della sua avventura dall'informatica al program management, quali sono i compiti di un Program Manager nelle Big Tech e della sua esperienza da freelance come Tech Startup Advisor.",
			},
			{
				category: "event",
				guest_id: [39],
				title: "From C++ To Kernel Engineering",
				href: "/superheroes",
				year: "2023",
				day: "22",
				month: "05",
				descriprion:
				"Vladislav è Senior MTS Kernel Engineer a VMware, ci racconterà della sua avventura da developer in C++ a Kernel Engineer. Durante il talk Vladislav parlerà della sua esperienza nel mondo del lavoro fin da giovane, la passione per Linux, il suo contributo personale al mondo open source ed il trasferimento in Silicon Valley.",
			},
			{
				category: "event",
				guest_id: [38],
				title: "Quantum Computing is like magic",
				href: "/superheroes",
				year: "2023",
				day: "19",
				month: "05",
				descriprion:
				"Jordan is Tech Evangelist AWS Braket. In this talk she will talk about Quantum Computing, especially in Amazon",
			},
			{
				category: "event",
				guest_id: [37],
				title: "Sognando la California",
				href: "/superheroes",
				year: "2023",
				day: "15",
				month: "05",
				descriprion:
				"Alberto è HPC DevOps Engineer in Seqera Labs. Dopo aver passato un periodo a Berkeley è tornato in Italia e non vede l'ora di raccontarci come si vive in California",
			},
			{
				category: "event",
				guest_id: [36],
				title: "My path to Crazyness",
				href: "/superheroes",
				year: "2023",
				day: "04",
				month: "04",
				descriprion:
				"Alberto è Senior Machine Learning Engineer a Meta, ci racconterà della sua 'folle' esperienza. Durante il talk Alberto parlerà della sua esperienza e preparazione per i colloqui prima in JP Morgan e poi in Meta.",
			},
			{
				category: "event",
				guest_id: [35],
				title: "My path to Google",
				href: "/superheroes",
				year: "2023",
				day: "29",
				month: "03",
				descriprion:
				"Antonino è Site Reliability Manager a Google, ci racconterà della sua molteplice esperienza nelle big tech. Durante il talk avremo modo di capire come Antonino sia arrivato prima alla Sun Microsystems, poi Amazon ed infine in Google.",
			},
			{
				category: "event",
				guest_id: [34],
				title: "Augmented and Virtual Reality from a Software Engineer point of view",
				href: "/superheroes",
				year: "2023",
				day: "27",
				month: "02",
				descriprion:
				"Alberto Taiuti è 3D Software Engineer in Skydio, ha lavorato su Augmented e Virtual Reality in Apple ed ha co-fondato Luma AI.",
			},
			{
				category: "event",
				guest_id: [33],
				title: "Antonio Gulli live a Pisa",
				href: "/superheroes",
				year: "2023",
				day: "20",
				month: "02",
				descriprion:
				"Antonio Gulli è Senior Director in Google. In questa live presso l'Università di Pisa avremo modo di scoprire la storia di Antonio, da Pisa fino a Zurigo in Google passando per il dottorato di ricerca e la sua esperienza nel mondo startup e nella difficoltà di portare una azienda come Ask ad investire in Italia.",
			},
			{
				category: "event",
				guest_id: [32],
				title: "My path to Software Engineering at Google",
				href: "/superheroes",
				year: "2023",
				day: "06",
				month: "02",
				descriprion:
				"Nancy is a Software Engineer in Google. In this talk we deep dive on how to grok the technical interview process",
			},
			{
				category: "event",
				guest_id: [31],
				title: "My path to Google",
				href: "/superheroes",
				year: "2023",
				day: "02",
				month: "02",
				descriprion:
				"Simone è Machine Learning Software Engineer in Google. Durante il talk ci parlerà di come perfezionare il CV e prepararsi ai colloqui per le FAANG",
			},
		],
	},
	{
		year: "2022",
		events: [
			{
				category: "event",
				guest_id: [27],
				title: "From Open Source to Microsoft",
				href: "/superheroes",
				year: "2022",
				day: "12",
				month: "12",
				descriprion:
				"Lorenzo è Senior Software Engineer a Microsoft ci racconterà del fil rouge della sua carriera: open source. Durante il talk avremo modo di chiedere a Lorenzo come si faccia a contribuire a progetti open source e quanto possano essere utili per farsi notare dalle big tech.",
			},
			{
				category: "event",
				guest_id: [29],
				title: "My path to Meta",
				href: "/superheroes",
				year: "2022",
				day: "5",
				month: "12",
				descriprion:
				"Alberto è Production Engineer a Meta ed in questo talk avremo l’occasione di farci raccontare del suo percorso che passa attraverso l’amore per Linux, il Machine Learning, l'odio nei confronti dei miner delle crypto ed essere assunto in una Big Tech come Meta.",
			},
			{
				category: "event",
				guest_id: [30],
				title: "La carriera piena di intoppi (?) di Roberto Clapis",
				href: "/superheroes",
				year: "2022",
				day: "28",
				month: "11",
				descriprion:
				"Come si fa a diventare esperti in un ambito tecnico? Quali sono i rischi di tentare questo tipo di carriera? A che punto dell'evoluzione professionale si può essere sicuri nel proprio percorso, e quando invece si rischia di commettere sviste evitabili? Questo talk proverà a dare delle risposte ripercorrendo la carriera piena di intoppi di Roberto Clapis.",
			},
			{
				category: "event",
				guest_id: [28],
				title: "Dall'industria all'accademia",
				href: "/superheroes",
				year: "2022",
				day: "14",
				month: "11",
				descriprion: "Fabrizio ha avuto in passato in ricerca in aziende come Yahoo! Research e Facebook AI. Oltre a queste esperienze di ricerca, è stato anche software engineer sempre a Facebook. Oggi è professore ordinario alla Sapienza.",
			},
			{
				category: "event",
				guest_id: [6],
				title: "Come affrontare il colloquio nelle FAANG",
				href: "/superheroes",
				year: "2022",
				day: "7",
				month: "11",
				descriprion: "Nicola è Senior Android Engineer e durante il talk ci racconterà di come funziona il processo di colloquio nelle Big Tech company",
			},
			{
				category: "event",
				guest_id: [26],
				title: "Un italiano in Nvidia",
				href: "/superheroes",
				year: "2022",
				day: "24",
				month: "10",
				descriprion: "Marco ci racconterà del suo percorso lavorativo ed, in particolare, di cosa lo ha condotto ad Nvidia!",
			},
			{
				category: "event",
				guest_id: [14],
				title: "Scrivere un CV per le FAANG",
				href: "/superheroes",
				year: "2022",
				day: "17",
				month: "10",
				descriprion: "Diego Ceccarelli, AI Team Leader a Bloomberg, ci racconterà come strutturare un CV da mandare ad una Big Tech company!",
			},
			{
				category: "event",
				guest_id: [1],
				title: "Google AMA con Christian Burrini",
				href: "/superheroes",
				year: "2022",
				day: "24",
				month: "06",
				descriprion: "Evento in presenza a Pisa con Christian Burrini, sessione di Ask me anything",
			},
			{
				category: "event",
				guest_id: [22],
				title: "Da Pisa a Twitter con Diego Puppin",
				href: "/superheroes",
				year: "2022",
				day: "02",
				month: "05",
				descriprion:
					"Diego è Staff Software Engineer a Twitter e, Lunedì 2 Maggio alle 21:30, avremo il piacere di ospitarlo a parlarci del suo percorso che lo ha portato a Twitter! ",
			},
			{
				category: "event",
				guest_id: [23],
				title: "Dal Texas Instruments Ti99/4a alla Silicon Valley",
				href: "/superheroes",
				year: "2022",
				day: "26",
				month: "04",
				descriprion:
					"Enrico Zimuel, Principal Software Engineer ad Elastic, ci racconterà della sua esperienza lavorativa e di cosa è significato per lui lavorare in Silicon Valley. Per chi non conoscesse Elastic, è una società quotata in borsa Americana - Olandese. Elasticsearch, è il motore di ricerca da loro sviluppato ed usato da grandi aziende come eBay, Wikipedia, Yelp, Uber, Lyft, Tinder e Netflix.",
			},
			{
				category: "event",
				guest_id: [],
				title: "Path to Google leveraging competing offers",
				href: "/superheroes",
				year: "2022",
				day: "11",
				month: "04",
				descriprion:
					"Ludovico Bessi, Software Engineer - Machine Learning, di Google ci racconterà di alcune tips sul processo di recruiting e sulla negoziazione delle offerte di lavoro nelle Big Tech.",
			},
			{
				category: "event",
				guest_id: [20, 19, 15],
				title: "",
				href: "/superheroes",
				year: "2022",
				day: "21",
				month: "03",
				descriprion:
					"Lunedì 21/03 alle 18:30 avremo il talk di 3 ragazzi di Apple! Filippo Bigarella - Security Engineer Niccolo’ Giovannelli - Engineering Project Manager Giovanni Tarducci - Senior iOS Engineer Filippo, Niccolo’ e Giovanni ci racconteranno della loro esperienza e di cosa li ha portati ad Apple!",
			},
			{
				category: "event",
				guest_id: [24],
				title: "Mia-Platform",
				href: "/superheroes",
				year: "2022",
				day: "14",
				month: "03",
				descriprion:
					"On Monday 14/03 at 18:30, Michel Murabito will talk about Mia-Platform. Is Mia-Platform a FAANG company? Obviously no. But for sure is one of the most promising Italian tech companies that acquired international attention. We want to encourage these realities giving Mia-Platform a space to talk about itself :)",
			},
			{
				category: "event",
				guest_id: [25],
				title: "Google talk",
				href: "/superheroes",
				year: "2022",
				day: "04",
				month: "03",
				descriprion:
					"This Friday at 18:30, Yerlan Baiturinov will talk about his path to Google. It is an occasion for us to ask him some questions :)",
			},
			{
				category: "event",
				guest_id: [24],
				title: "Netflix",
				href: "/superheroes",
				year: "2022",
				day: "25",
				month: "02",
				descriprion:
					"We are glad to announce that, on Monday 28/02 at 19:00, Mattia Toso, Senior Software Engineer at Netflix, will talk about his experience!",
			},
			{
				category: "event",
				guest_id: [5],
				title: "Google",
				href: "/superheroes",
				year: "2022",
				day: "07",
				month: "02",
				descriprion:
					"We are glad to announce that on Monday 7/02 at 18:00, Shahed Shahriar SRE @Google will reveal to us some tips to prepare for Coding Competitions like Google Hashcode! We recall that we created a Virtual Hub for the Hashcode with the name [Italy] SuperHeroes Valley - GDG Pisa - DSC Pisa - GDG Cloud Torino. So, if you intend to participate in the Hashcode, feel free to join us :)",
			},
		],
	},
	{
		year: "2021",
		events: [],
	},
	{
		year: "2020",
		events: [],
	},
];