export const PastEvents = [
	{
		year: "2023",
		events: [],
	},
	{
		year: "2022",
		events: [
			{
				category: "event",
				guest_id: [27],
				title: "From Open Source to Microsoft",
				href: "/superheroes",
				year: "2022",
				day: "12",
				month: "12",
				descriprion:
				"Lorenzo è Senior Software Engineer a Microsoft ci racconterà del fil rouge della sua carriera: open source. Durante il talk avremo modo di chiedere a Lorenzo come si faccia a contribuire a progetti open source e quanto possano essere utili per farsi notare dalle big tech.",
			},
			{
				category: "event",
				guest_id: [29],
				title: "My path to Meta",
				href: "/superheroes",
				year: "2022",
				day: "5",
				month: "12",
				descriprion:
				"Alberto è Production Engineer a Meta ed in questo talk avremo l’occasione di farci raccontare del suo percorso che passa attraverso l’amore per Linux, il Machine Learning, l'odio nei confronti dei miner delle crypto ed essere assunto in una Big Tech come Meta.",
			},
			{
				category: "event",
				guest_id: [30],
				title: "La carriera piena di intoppi (?) di Roberto Clapis",
				href: "/superheroes",
				year: "2022",
				day: "28",
				month: "11",
				descriprion:
				"Come si fa a diventare esperti in un ambito tecnico? Quali sono i rischi di tentare questo tipo di carriera? A che punto dell'evoluzione professionale si può essere sicuri nel proprio percorso, e quando invece si rischia di commettere sviste evitabili? Questo talk proverà a dare delle risposte ripercorrendo la carriera piena di intoppi di Roberto Clapis.",
			},
			{
				category: "event",
				guest_id: [28],
				title: "Dall'industria all'accademia",
				href: "/superheroes",
				year: "2022",
				day: "14",
				month: "11",
				descriprion: "Fabrizio ha avuto in passato in ricerca in aziende come Yahoo! Research e Facebook AI. Oltre a queste esperienze di ricerca, è stato anche software engineer sempre a Facebook. Oggi è professore ordinario alla Sapienza.",
			},
			{
				category: "event",
				guest_id: [6],
				title: "Come affrontare il colloquio nelle FAANG",
				href: "/superheroes",
				year: "2022",
				day: "7",
				month: "11",
				descriprion: "Nicola è Senior Android Engineer e durante il talk ci racconterà di come funziona il processo di colloquio nelle Big Tech company",
			},
			{
				category: "event",
				guest_id: [26],
				title: "Un italiano in Nvidia",
				href: "/superheroes",
				year: "2022",
				day: "24",
				month: "10",
				descriprion: "Marco ci racconterà del suo percorso lavorativo ed, in particolare, di cosa lo ha condotto ad Nvidia!",
			},
			{
				category: "event",
				guest_id: [14],
				title: "Scrivere un CV per le FAANG",
				href: "/superheroes",
				year: "2022",
				day: "17",
				month: "10",
				descriprion: "Diego Ceccarelli, AI Team Leader a Bloomberg, ci racconterà come strutturare un CV da mandare ad una Big Tech company!",
			},
			{
				category: "event",
				guest_id: [1],
				title: "Google AMA con Christian Burrini",
				href: "/superheroes",
				year: "2022",
				day: "24",
				month: "06",
				descriprion: "Evento in presenza a Pisa con Christian Burrini, sessione di Ask me anything",
			},
			{
				category: "event",
				guest_id: [22],
				title: "Da Pisa a Twitter con Diego Puppin",
				href: "/superheroes",
				year: "2022",
				day: "02",
				month: "05",
				descriprion:
					"Diego è Staff Software Engineer a Twitter e, Lunedì 2 Maggio alle 21:30, avremo il piacere di ospitarlo a parlarci del suo percorso che lo ha portato a Twitter! ",
			},
			{
				category: "event",
				guest_id: [23],
				title: "Dal Texas Instruments Ti99/4a alla Silicon Valley",
				href: "/superheroes",
				year: "2022",
				day: "26",
				month: "04",
				descriprion:
					"Enrico Zimuel, Principal Software Engineer ad Elastic, ci racconterà della sua esperienza lavorativa e di cosa è significato per lui lavorare in Silicon Valley. Per chi non conoscesse Elastic, è una società quotata in borsa Americana - Olandese. Elasticsearch, è il motore di ricerca da loro sviluppato ed usato da grandi aziende come eBay, Wikipedia, Yelp, Uber, Lyft, Tinder e Netflix.",
			},
			{
				category: "event",
				guest_id: [],
				title: "Path to Google leveraging competing offers",
				href: "/superheroes",
				year: "2022",
				day: "11",
				month: "04",
				descriprion:
					"Ludovico Bessi, Software Engineer - Machine Learning, di Google ci racconterà di alcune tips sul processo di recruiting e sulla negoziazione delle offerte di lavoro nelle Big Tech.",
			},
			{
				category: "event",
				guest_id: [20, 19, 15],
				title: "",
				href: "/superheroes",
				year: "2022",
				day: "21",
				month: "03",
				descriprion:
					"Lunedì 21/03 alle 18:30 avremo il talk di 3 ragazzi di Apple! Filippo Bigarella - Security Engineer Niccolo’ Giovannelli - Engineering Project Manager Giovanni Tarducci - Senior iOS Engineer Filippo, Niccolo’ e Giovanni ci racconteranno della loro esperienza e di cosa li ha portati ad Apple!",
			},
			{
				category: "event",
				guest_id: [24],
				title: "Mia-Platform",
				href: "/superheroes",
				year: "2022",
				day: "14",
				month: "03",
				descriprion:
					"On Monday 14/03 at 18:30, Michel Murabito will talk about Mia-Platform. Is Mia-Platform a FAANG company? Obviously no. But for sure is one of the most promising Italian tech companies that acquired international attention. We want to encourage these realities giving Mia-Platform a space to talk about itself :)",
			},
			{
				category: "event",
				guest_id: [25],
				title: "Google talk",
				href: "/superheroes",
				year: "2022",
				day: "04",
				month: "03",
				descriprion:
					"This Friday at 18:30, Yerlan Baiturinov will talk about his path to Google. It is an occasion for us to ask him some questions :)",
			},
			{
				category: "event",
				guest_id: [24],
				title: "Netflix",
				href: "/superheroes",
				year: "2022",
				day: "25",
				month: "02",
				descriprion:
					"We are glad to announce that, on Monday 28/02 at 19:00, Mattia Toso, Senior Software Engineer at Netflix, will talk about his experience!",
			},
			{
				category: "event",
				guest_id: [5],
				title: "Google",
				href: "/superheroes",
				year: "2022",
				day: "07",
				month: "02",
				descriprion:
					"We are glad to announce that on Monday 7/02 at 18:00, Shahed Shahriar SRE @Google will reveal to us some tips to prepare for Coding Competitions like Google Hashcode! We recall that we created a Virtual Hub for the Hashcode with the name [Italy] SuperHeroes Valley - GDG Pisa - DSC Pisa - GDG Cloud Torino. So, if you intend to participate in the Hashcode, feel free to join us :)",
			},
		],
	},
	{
		year: "2021",
		events: [],
	},
	{
		year: "2020",
		events: [],
	},
];