export const superheroes = [
	{
		id: 1,
		name: "Cristian Burrini",
		href: "",
		company: "Google",
		image: "./guests/cristian_burrini.webp",
		link: "http://google.com",
		companyLogo: "./logos/google.png",
	},
	{
		id: 2,
		name: "Lisa Vitolo",
		href: "",
		company: "Google",
		image: "./guests/default_img.png",
		link: "",
		companyLogo: "./logos/google.png",
	},
	{
		id: 3,
		name: "Federico Scloza",
		href: "",
		company: "Google",
		image: "./guests/default_img.png",
		link: "",
		companyLogo: "./logos/google.png",
	},
	{
		id: 4,
		name: "Samuele Maci",
		href: "",
		company: "Meta",
		image: "./guests/samuele_maci.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 5,
		name: "Shahed Shahriar",
		href: "",
		company: "Google",
		image: "./guests/shahed.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 6,
		name: "Nicola Corti",
		href: "",
		company: "Meta",
		image: "./guests/nicola_corti.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 7,
		name: "Diego Colombo",
		href: "",
		company: "Microsoft",
		image: "./guests/diego_colombo.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 8,
		name: "Maurizio Sciglio",
		href: "/superheroes",
		company: "Epic Games",
		image: "./guests/maurizio_sciglio.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 9,
		name: "Roberto Gambuzzi",
		href: "",
		company: "Google",
		image: "./guests/roberto_gambuzzi.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 10,
		name: "Luciano Mammino",
		href: "",
		company: "fourTheorem",
		image: "./guests/luciano_mammino.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 11,
		name: "Anton Yegorin",
		href: "",
		company: "IBM",
		image: "./guests/anton_yegorin.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 12,
		name: "Silvia Trebini",
		href: "",
		company: "Bending Spoons ",
		image: "./guests/silvia_trebini.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 13,
		name: "Federico Cergol",
		href: "",
		company: "Bending Spoons",
		image: "./guests/federico_cergol.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 14,
		name: "Diego Ceccarelli",
		href: "",
		company: "Bloomberg",
		image: "./guests/diego_ceccarelli.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 15,
		name: "Filippo Bigarella",
		href: "",
		company: "Apple",
		image: "./guests/filippo_bigarella.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 16,
		name: "Erika J. Yuag",
		href: "",
		company: "Microsoft",
		image: "./guests/erika_yuag.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 17,
		name: "Francesca Cucinotta",
		href: "",
		company: "Bloomberg",
		image: "./guests/francesca_cucinotta.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 18,
		name: "Mattia Toso",
		href: "",
		company: "Netflix",
		image: "./guests/mattia_toso.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 19,
		name: "Niccolò Giovannelli",
		href: "",
		company: "Apple",
		image: "./guests/niccolo_giovannelli.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 20,
		name: "Giovanni Tarducci",
		href: "",
		company: "Apple",
		image: "./guests/default_img.png",
		link: "",
		companyLogo: "",
	},
	{
		id: 21,
		name: "Ludovico Bessi",
		href: "",
		company: "Google",
		image: "./guests/ludovico_bessi.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 22,
		name: "Diego Puppin",
		href: "",
		company: "Twitter",
		image: "./guests/diego_puppin.webp",
		link: "",
		companyLogo: "",
	},
	{
		id: 23,
		name: "Enrico Zimuel",
		href: "",
		company: "Elastic",
		image: "./guests/default_img.png",
		link: "",
		companyLogo: "",
	},
	{
		id: 24,
		name: "Mich Murabito",
		href: "",
		company: "Mia Platform",
		image: "./guests/default_img.png",
		link: "",
		companyLogo: "",
	},
	{
		id: 25,
		name: " Yerlan Baiturinov",
		href: "",
		company: "Google",
		image: "./guests/default_img.png",
		link: "",
		companyLogo: "",
	},
];
