export const superheroes = [
	{
		id: 1,
		name: "Cristian Burrini",
		href: "",
		company: "Google",
		image: "./guests/cristian_burrini.webp",
	},
	{
		id: 2,
		name: "Lisa Vitolo",
		href: "",
		company: "Google",
		image: "./guests/default_image.webp",
	},
	{
		id: 3,
		name: "Federico Scloza",
		href: "",
		company: "Google",
		image: "./guests/default_image.webp",
	},
	{
		id: 4,
		name: "Samuele Maci",
		href: "",
		company: "Meta",
		image: "./guests/samuele_maci.webp",
	},
	{
		id: 5,
		name: "Shahed Shahriar",
		href: "",
		company: "Google",
		image: "./guests/shahed.webp",
	},
	{
		name: "Nicola Corti",
		href: "",
		company: "Meta",
		image: "./guests/nicola_corti.webp",
	},
	{
		name: "Diego Colombo",
		href: "",
		company: "Microsoft",
		image: "./guests/diego_colombo.webp",
	},
	{
		name: "Maurizio Sciglio",
		href: "/superheroes",
		company: "Epic Games",
		image: "./guests/maurizio_sciglio.webp",
	},
	{
		name: "Roberto Gambuzzi",
		href: "",
		company: "Google",
		image: "./guests/roberto_gambuzzi.webp",
	},
	{
		name: "Luciano Mammino",
		href: "",
		company: "fourTheorem",
		image: "./guests/luciano_mammino.webp",
	},
	{
		name: "Anton Yegorin",
		href: "",
		company: "IBM",
		image: "./guests/anton_yegorin.webp",
	},
	{
		name: "Silvia Trebini",
		href: "",
		company: "Bending Spoons ",
		image: "./guests/silvia_trebini.webp",
	},
	{
		name: "Federico Cergol",
		href: "",
		company: "Bending Spoons",
		image: "./guests/federico_cergol.webp",
	},
	{
		name: "Diego Ceccarelli",
		href: "",
		company: "Bloomberg",
		image: "./guests/diego_ceccarelli.webp",
	},
	{
		name: "Filippo Bigarella",
		href: "",
		company: "Apple",
		image: "./guests/filippo_bigarella.webp",
	},
	{
		name: "Erika J. Yuag",
		href: "",
		company: "Microsoft",
		image: "./guests/erika_yuag.webp",
	},
	{
		name: "Francesca Cucinotta",
		href: "",
		company: "Bloomberg",
		image: "./guests/francesca_cucinotta.webp",
	},
	{
		name: "Mattia Toso",
		href: "",
		company: "Netflix",
		image: "./guests/mattia_toso.webp",
	},
	{
		name: "Niccolò Giovannelli",
		href: "",
		company: "Apple",
		image: "./guests/niccolo_giovannelli.webp",
	},
	{
		name: "Giovanni Tarducci",
		href: "",
		company: "Apple",
		image: "./guests/default_image.webp",
	},
	{
		name: "Ludovico Bessi",
		href: "",
		company: "Google",
		image: "./guests/ludovico_bessi.webp",
	},
	{
		name: "Diego Puppin",
		href: "",
		company: "Twitter",
		image: "./guests/diego_puppin.webp",
	},
];
