export const TeamList = [
	{
		id: 1,
		name: "Remo Andreoli",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Co-founder, Board Member",
		image: "./team/remo_andreoli.jpeg",
		bio: "Ph.D. Student @Sant'Anna School of Advanced Studies",
	},
	{
		id: 2,
		name: "Alessandro Berti",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Co-founder, Board Member, Head of Mentorship",
		image: "./team/alessandro_berti.webp",
		bio: "Ph.D. Student @University of Pisa",
	},
	{
		id: 3,
		name: "Luca Corbucci",
		href: "https://lucacorbucci.me",
		company: "Ph.D. Student @University of Pisa",
		linkedin: "https://www.linkedin.com/in/lucacorbucci/",
		github: "https://github.com/lucacorbucci",
		twitter: "",
		mastodon: "https://mastodon.cloud/@lucacorbucci",
		role: "Co-founder",
		image: "./team/luca_corbucci.webp",
		bio: "PhD Student @ University of Pisa - I suoi interesse di ricerca riguardano Privacy Preserving Machine Learning e Federated Learning. Nel tempo libero è podcaster al PointerPodcast.",
	},
	{
		id: 4,
		name: "Eugenio Paluello",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Co-founder, Board Member",
		image: "./team/eugenio_paluello.webp",
		bio: "Blockchain Engineer@Kakarot zkEVM",
	},
	{
		id: 5,
		name: "Angela Carraro",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/angela.jpg",
		bio: "Data Analyst @ Amazon.",
	},
	{
		id: 5,
		name: "Riccardo Sarpietro",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Head of Talks",
		image: "./team/riccardo.png",
		bio: "PhD student in Computer Engineering. Data Scientist @ STMicroelectronics",
	},
	{
		id: 6,
		name: "Stefano Ivancich",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Head of Training",
		image: "./team/stefano.png",
		bio: "Software Engineer @ Uber, Ex-amazon Software Engineer. Passioned about Business and make money with technology.",
	},
	{
		id: 7,
		name: "Simone Nicol",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/simone.png",
		bio: "Software Engineer @Bynder. Ex Software Engineer Intern @Amazon. ",
	},
	{
		id: 7,
		name: "Emanuele Triuzzi",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/emanuele_triuzzi.webp",
		bio: "Software Engineer @ Bending Spoons",
	},
	{
		id: 8,
		name: "Nicolas Schirosi",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/nicolas_schirosi.webp",
		bio: "",
	},
	{
		id: 9,
		name: "Francesco Paolo Liuzzi",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/francesco_paolo_liuzzi.webp",
		bio: "",
	},
];
