export const TeamList = [
	{
		id: 1,
		name: "Remo Andreoli",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Co-founder",
		image: "./team/remo_andreoli.jpeg",
        bio: "Ph.D. Student @Sant'Anna School of Advanced Studies",
	},
	{
		id: 2,
		name: "Alessandro Berti",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Co-founder",
		image: "./team/alessandro_berti.webp",
        bio: 'Ph.D. Student @University of Pisa',
	},
	{
		id: 3,
		name: "Luca Corbucci",
		href: "https://lucacorbucci.me",
		company: "Ph.D. Student @University of Pisa",
		linkedin: "https://www.linkedin.com/in/lucacorbucci/",
		github: "https://github.com/lucacorbucci",
		twitter: "",
        mastodon: "https://mastodon.cloud/@lucacorbucci",
		role: "Co-founder",
		image: "./team/luca_corbucci.webp",
        bio: "PhD Student @ University of Pisa - I suoi interesse di ricerca riguardano Privacy Preserving Machine Learning e Federated Learning. Nel tempo libero è podcaster al PointerPodcast.",
	},
	{
		id: 4,
		name: "Eugenio Paluello",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Co-founder",
		image: "./team/eugenio_paluello.webp",
        bio: 'Blockchain Developer @ Polygon',
	},
    {
		id: 5,
		name: "Angela Carraro",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/angela.jpg",
        bio: 'Data Analyst @ Amazon.',
	},
    {
		id: 5,
		name: "Alessandro Stefanelli",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/alessandro.jpg",
        bio: 'Studente Magistrale in Intelligenza Artificiale. Appassionato di fumetti e di fantascienza',
	},
    {
		id: 5,
		name: "Riccardo Sarpietro",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/riccardo.png",
        bio: 'PhD student in Computer Engineering with major topics in Reinforcement Learning and Computer Vision. Ex-STMicroelectronics Data Scientist',
	},
    {
		id: 6,
		name: "Stefano Ivancich",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/stefano.png",
        bio: 'Software Engineer @ Uber Ex-amazon Software Engineer. Passioned about Business and make money with technology.',
	},
    {
		id: 7,
		name: "Simone Nicol",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/simone.png",
        bio: 'Software Engineer @Bynder. Ex Software Engineer Intern @Amazon. ',
	},
    {
		id: 7,
		name: "Emanuele Triuzzi",
		href: "",
		company: "",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/emanuele.jpg",
        bio: 'Software Engineer @ Bending Spoons',
	},
];
