export const TeamList = [
	{
		id: 1,
		name: "Remo Andreoli",
		href: "",
		company: "Ph.D. Student @Sant'Anna School of Advanced Studies",
		linkedin: "",
		github: "",
		twitter: "",
		role: "manager",
		image: "./team/remo_andreoli.webp",
	},
	{
		id: 2,
		name: "Alessandro Berti",
		href: "",
		company: "Ph.D. Student @University of Pisa ",
		linkedin: "",
		github: "",
		twitter: "",
		role: "manager",
		image: "./team/alessandro_berti.webp",
	},
	{
		id: 3,
		name: "Luca Corbucci",
		href: "https://lucacorbucci.me",
		company: "Ph.D. Student @University of Pisa",
		linkedin: "https://www.linkedin.com/in/lucacorbucci/",
		github: "https://github.com/lucacorbucci",
		twitter: "https://twitter.com/lucacorbucci",
		role: "manager",
		image: "./team/luca_corbucci.webp",
	},
	{
		id: 4,
		name: "Eugenio Paluello",
		href: "",
		company: "Blockchain Developer @ Polygon",
		linkedin: "",
		github: "",
		twitter: "",
		role: "manager",
		image: "./team/eugenio_paluello.webp",
	},
];
