export const TeamList = [
	{
		id: 1,
		name: "Remo Andreoli",
		href: "",
		company: "Ph.D. Student @Sant'Anna School of Advanced Studies",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Co-founder",
		image: "./team/remo_andreoli.jpeg",
        bio: 'Ultricies massa malesuada viverra cras lobortis.Ultricies massa malesuada viverra cras lobortis.Ultricies massa malesuada viverra cras lobortis.Ultricies massa malesuada viverra cras lobortis. Tempor orci hac ligula dapibus mauris sit ut eu. Eget turpis urna maecenas cras. Nisl dictum.',
	},
	{
		id: 2,
		name: "Alessandro Berti",
		href: "",
		company: "Ph.D. Student @University of Pisa ",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Co-founder",
		image: "./team/alessandro_berti.webp",
        bio: 'Ultricies massa malesuada viverra cras lobortis. Tempor orci hac ligula dapibus mauris sit ut eu. Eget turpis urna maecenas cras. Nisl dictum.',
	},
	{
		id: 3,
		name: "Luca Corbucci",
		href: "https://lucacorbucci.me",
		company: "Ph.D. Student @University of Pisa",
		linkedin: "https://www.linkedin.com/in/lucacorbucci/",
		github: "https://github.com/lucacorbucci",
		twitter: "https://twitter.com/lucacorbucci",
		role: "Co-founder",
		image: "./team/luca_corbucci.webp",
        bio: "PhD Student @ University of Pisa - I suoi interesse di ricerca riguardano Privacy Preserving Machine Learning e Federated Learning. Nel tempo libero è podcaster al PointerPodcast.",
	},
	{
		id: 4,
		name: "Eugenio Paluello",
		href: "",
		company: "Blockchain Developer @ Polygon",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Co-founder",
		image: "./team/eugenio_paluello.webp",
        bio: 'Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Tempor orci hac ligula dapibus mauris sit ut eu. Eget turpis urna maecenas cras. Nisl dictum.',
	},
    {
		id: 5,
		name: "Angela Carraro",
		href: "",
		company: "Blockchain Developer @ Polygon",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/eugenio_paluello.webp",
        bio: 'Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Tempor orci hac ligula dapibus mauris sit ut eu. Eget turpis urna maecenas cras. Nisl dictum.',
	},
    {
		id: 5,
		name: "Alessandro Stefanelli",
		href: "",
		company: "Blockchain Developer @ Polygon",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/eugenio_paluello.webp",
        bio: 'Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Tempor orci hac ligula dapibus mauris sit ut eu. Eget turpis urna maecenas cras. Nisl dictum.',
	},
    {
		id: 5,
		name: "Riccardo Sarpietro",
		href: "",
		company: "Blockchain Developer @ Polygon",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/eugenio_paluello.webp",
        bio: 'Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Tempor orci hac ligula dapibus mauris sit ut eu. Eget turpis urna maecenas cras. Nisl dictum.',
	},
    {
		id: 6,
		name: "Stefano Ivancich",
		href: "",
		company: "Blockchain Developer @ Polygon",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/eugenio_paluello.webp",
        bio: 'Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Tempor orci hac ligula dapibus mauris sit ut eu. Eget turpis urna maecenas cras. Nisl dictum.',
	},
    {
		id: 7,
		name: "Simone Nicol",
		href: "",
		company: "Blockchain Developer @ Polygon",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/eugenio_paluello.webp",
        bio: 'Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Tempor orci hac ligula dapibus mauris sit ut eu. Eget turpis urna maecenas cras. Nisl dictum.',
	},
    {
		id: 7,
		name: "Emanuele Triuzzi",
		href: "",
		company: "Blockchain Developer @ Polygon",
		linkedin: "",
		github: "",
		twitter: "",
		role: "Community Manager",
		image: "./team/eugenio_paluello.webp",
        bio: 'Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Ultricies massa malesuada viverra cras lobortis. Tempor orci hac ligula dapibus mauris sit ut eu. Eget turpis urna maecenas cras. Nisl dictum.',
	},
];
