baseURL = "//superheroesvalley.fun"
languageCode = "en-us"
title = "Superheroes Valley"
publishDir = "public"

[params]
    mainbg = "//source.unsplash.com/collection/43861294/1920x1080"
    name = "SuperheroesValley.fun"
    mainTitle = "Hello, Superhero!"
    mainText = "The superheroes factory"


[menus]
    [[menu.main]]
        identifier = "talks"
        name = "Talks"
        url = "#talks"
    [[menu.main]]
        identifier = "guests"
        name = "Guests"
        url = "#guests"
    [[menu.main]]
        identifier = "join_us"
        name = "Join_us"
        url = "#join_us"
    [[menu.main]]
        identifier = "about_us"
        name = "About_us"
        url = "#about_us"
